import Head from "next/head"
import { Inter } from "next/font/google"
import SearchInput from "@/client/components/ui/Input/SearchInput"
import Players from "@/client/components/Players"
import { useEffect, useState } from "react"
import { PlayerData } from "@types"
import Pagination from "@/client/components/Pagination"

export default function Home() {
    const [players, setPlayers] = useState<PlayerData>({
        data: [],
        limit: 6,
        page: 1,
    })
    const [search, setSearch] = useState<string>("")
    const [page, setPage] = useState<number>(1);

    const handleSearch = (e: any) => setSearch(e.target.value)
    
    // imprative way
    const handlePagination = (pageId: number) => {
        fetch(`/api/players?search=${search}&limit=6&page=${pageId}`)
        .then((res) => res.json())
        .then((data: any) => {
            console.log(data)
            setPlayers(data)
            setPage(data.page)
        })
        .catch((err) => console.log(err))
    }

    // declarative way
    useEffect(() => {
        const controller =  new AbortController();
            fetch(`/api/players?search=${search}&limit=6&page=${page}`,  { signal: controller.signal })
                .then((res) => res.json())
                .then((data: any) => {
                    console.log(data)
                    setPlayers(data)
                    setPage(prevPage => data.page)
                })
                .catch((err) => {
                    if(err.name == 'AbortError')
                        console.log('The User cancelled the fetch');
                    else
                        console.log(err);
                        
                })

        return () => {
            console.log('cancellced!');
            controller.abort();
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [search])

    return (
        <>
            <Head>
                <title>Fifa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="container mx-auto flex flex-col gap-4 justify-center items-center px-4 mt-6">
                    <SearchInput
                        className="w-[60%] border-b-2"
                        onChange={handleSearch}
                        value={search}
                    />
                    <Players players={players.data} />
                    <Pagination pagination={handlePagination} pageId={page} />
                </div>
            </main>
        </>
    )
}
